blank_issues_enabled: false
contact_links:
    - name: Discord Community
      url: https://discord.gg/jatU44PavX
      about: The Veteran Database - A place to discuss VeteranDB, get help, ask questions, and more.
    - name: Facebook Community
      url: https://www.facebook.com/groups/veterandbcommunity/
      about: The Veteran Database - A place to discuss VeteranDB, get help, ask questions, and more.
