blank_issues_enabled: false
contact_links:
    - name: Discord
      url: https://discord.gg/jatU44PavX
      about: The Veteran Database Community, for general VeteranDB questions or help.
    - name: Facebook Group
      url: https://www.facebook.com/groups/veterandbcommunity/
      about: The Veteran Database Community, for general VeteranDB questions or help.
